### PR TITLE
Added option to hide just the left ribbon

### PR DESCRIPTION
**Pull request by ZibraMax**
Hi!

I wanted to hide the left ribbon and maintain the right ribbon, but the hide ribbon option only allows to hide both ribbons. 

The right ribbon is often used as the calendar/tasks/reminders panel. When the right ribbon is hid, there is no option to collapse that panel (It's the only reason why I wanted that ribbon).

I added the settings entry and a CSS class to hide just the left ribbon:

image

When is activated, the right ribbon don't hide:

image

Thanks for the plugin!

### CODE REVIEW

**Comment by kepano** [comment]
Thanks for your contribution! 

I need to think about this because it will cause breaking changes for many themes that depend on Hider.

Note that Obsidian offers hotkeys to toggle sidebars individually.

**Comment by brooksvb** [comment]
I would like to say that I just came across this plugin trying to find a way to hide the title bar, and the dead space on the right ribbon (don't need to waste that width for an expand/collapse button when I use hotkeys). I still want the left ribbon with the icons for certain actions though!

Any updates or thoughts on this change and enabling the option to hide either ribbon individually?

EDIT:
I solved this by adding a css snippet with the following:
```css
.workspace-ribbon.mod-right {
	display: none;
}
```

**Comment by nttldnknwn** [comment]
> Thanks for your contribution!
> 
> I need to think about this because it will cause breaking changes for many themes that depend on Hider.
> 
> Note that Obsidian offers hotkeys to toggle sidebars individually.

kepano, hi!
_I apologize for replying in this thread instead of creating a new Pull Request, I'm just not a programmer, I just created a profile just to leave this comment, tried to create a Pull Request but never figured out how to do it...._

If you don't mind, please consider adding a hide feature:
- File Explorer Icon
- Help Icon
- Change Sort Order Icon
- Current View (Read / Edit) Icon
- Close Icon
- More Options Icon
- Collapse (Left Sidebar) Icon

At the moment my workspace in Obsidian looks like this:
Screenshot_1

And I want to remove all unnecessary things that I do not use or use very rarely, so that my workspace looks something like this:
Screenshot_2

Conciseness and minimalism =)

Many thanks!!!

**Comment by kepano** [comment]
This is no longer relevant as right ribbon doesn't exist anymore in Obsidian 0.16+

**Pull request closed without merging**
